### ISSUE TITLE
px-tooltip does not position correctly inside an iframe.

### ISSUE THREAD

**Issue by runn-vermel** [PredixDev/px-tooltip#11]
# Submit an Issue
## Expected behavior and actual behavior:
- expected: when the smart-orientation attribute is specified, the tooltip should adjust  it's orientation to one that displays on the screen.
- Actual Behaviour: when inside an iframe, the tooltip does not detect it's position correctly, and can be hidden.
## Steps to reproduce the problem:
1. create a page with an iframe in it, calling a page that has px-tooltip aligned to the left, and turn on the smart orientation attribute on it.
## Environment (_component version number, Browser (including version), operating system, hardware, etc_):

version 0.6.8
all browsers
Mac
## Screenshots (_optional, but very helpful_):

![screen shot 2016-06-10 at 3 05 53 pm](https://cloud.githubusercontent.com/assets/4295921/15980038/e4034f9a-2f1c-11e6-90a9-ae324b232868.png)
## Code examples

Since this issue is inside an iframe, which calls another page, I can't create a codepen/jsfiddle.

**Comment by randyaskin** [comment]
Closing due to age. Latest version seems to work fine with an iframe.
