### ISSUE TITLE
tooltip text gets cropped with very long words

### ISSUE THREAD

**Issue by arcpato** [PredixDev/px-tooltip#12]
## Expected behavior and actual behavior:

Currently, the tooltip wraps around very long text that contains spaces, however, very long words get cropped. 

![screen shot 2016-06-15 at 5 31 13 pm](https://cloud.githubusercontent.com/assets/6137443/16102302/e27bc5da-3322-11e6-89c7-99d57e051cb1.png)

Long words should wrap around so the text is still readable within the tooltip.

**Comment by runn-vermel** [comment]
PR #13 fixed this.
