### ISSUE TITLE
tooltipParent is not defined in properties

### ISSUE THREAD

**Issue by zhangliying1** [PredixDev/px-tooltip#14]
px-tooltip 0.7.5 throws error when hover dom element. See screenshot below. The reason is tooltipParent is not defined in properties.

![image](https://cloud.githubusercontent.com/assets/15002822/17718481/142d5356-63c9-11e6-9bbd-59fc0b351652.png)

**Comment by randyaskin** [comment]
@zhangliying1 I've added the property definition in v0.7.7. Let us know if this issue can be closed.
