### ISSUE TITLE
PX-tooltip shows up abruptly when tooltips are rendered in dom-repeat after the list is initialised to an empty array.

### ISSUE THREAD

**Issue by sumeet-singh04** [PredixDev/px-tooltip#16]
Confirmed Bug.

Noticed an issue when using tooltip inside a dom-repeat. Initially the tooltip renders fine, but if on the click of a item, you initialise the array to an empty array, the last tooltip that was being shown renders at the top-left corner of the screen.

## Expected behavior and actual behavior:

Expected behavior: Tooltips should be destroyed when the element they are linked to is removed from the dom.

Actual Behavior: Tooltip is displayed on the top left corner of the screen and no further tooltips render on the page.

## Steps to reproduce the problem:
http://codepen.io/anon/pen/YpEOGO

1> Open the above CodePen
2> Click on any button on the page besides showme.
3> All buttons disappear, and a tooltip shows up on the top left corner of the screen
4> Click on showme.
5> The buttons reappear but now you cannot render any tooltip when user hovers over the buttons.

**Comment by benoitjchevalier** [comment]
Thanks for the codepen, that is really helpful for investigating the issue :)

**Comment by benoitjchevalier** [comment]
Fixed in v0.9.17

**Comment by sumeet-singh04** [comment]
Awsome. Thanks for the quick response.
