### ISSUE TITLE
Show Request Event name differs from documentation

### ISSUE THREAD

**Issue by kdinluks** [PredixDev/px-tooltip#18]
https://github.com/PredixDev/px-tooltip/blob/master/px-tooltip.html#L476
fires px-tooltip-request-show when the documentation says px-tooltip-show-request.

**Comment by randyaskin** [comment]
Thanks, good catch. I'll fix this tomorrow - Travis is still having issues after the Amazon S3 outage today, so our docs won't rebuild at the moment.
