### ISSUE TITLE
"follow-mouse" property does not work

### ISSUE THREAD

**Issue by gedesigntech** [PredixDev/px-tooltip#19]
# Submit an Issue

Hi,

Thanks for helping us improve the Predix UI platform by submitting an issue.

Before you begin, please check the list of existing issues to avoid submitting a duplicate issue.

To help us solve this issue as fast as possible, please fill out the following sections:

## Expected behavior and actual behavior:
Using follow-mouse, follow-mouse="true" the tooltip follows the mouse

## Steps to reproduce the problem:
Use follow-mouse or follow-mouse="true" in the codepen for the component in predix-ui.com

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
v0.10.17, Chrome 56, MacOS Sierra
## Code examples help us better understand the issue - follow the appropriate codepen for the component by going to https://predix-ui.com, finding the component in question, and clicking on the pencil icon under the demo.
        Once you've created your code example, you can save it under a new url.
        Please note that you should NOT use the same methods for production as the ones used in codepen - these methods are not production ready.

From CodePen:

<base href="https://polygit.org/px-*+PredixDev+*/components/">
<script src="webcomponentsjs/webcomponents-lite.min.js"></script>
<link href="polymer/polymer.html" rel="import">
<link rel="import" href="px-theme/px-theme-styles.html">
<style include="px-theme-styles" is="custom-style"></style>
<link href="px-tooltip/px-tooltip.html" rel="import">
<body>
<div><px-tooltip for="btn1" delay="50" tooltip-message="This is a tooltip message" orientation="auto" tooltip-style="light" follow-mouse="true"></px-tooltip><button id='btn1'>Hover over me</button></div>
</body>

**Comment by nonmetalhail** [comment]
The follow mouse is a bit confusing as it is not the best name and was spliced in for vis and not fully documented. To "follow mouse" you have to 1) manually supply your mouse coordinates via `mouse-coords` and 2) supply a hover target via the `for` attribute so it will only show when over that target. The hover target controls it's visibility. The mouse-coords control its position.

**Comment by gedesigntech** [comment]
Those points probably need to be mentioned in the predix-ui.com docs for this component.  It also shows there that mouseCoords had a default value, which can imply that they don't need to be supplied, unlike what you said above.  Same for "for".
