### ISSUE TITLE
"orientation" attribute is not obeyed

### ISSUE THREAD

**Issue by gedesigntech** [PredixDev/px-tooltip#20]
# Submit an Issue

Hi,

Thanks for helping us improve the Predix UI platform by submitting an issue.

Before you begin, please check the list of existing issues to avoid submitting a duplicate issue.

To help us solve this issue as fast as possible, please fill out the following sections:

## Expected behavior and actual behavior:
I used orientation="top", but tooltip still shows to the right

## Steps to reproduce the problem:
Use orientation="top" in an instance of px-tooltip

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
v0.10.17, Chrome 56, macOS Sierra

## Screenshots (_optional, but very helpful_):
Please see attachment (CodePen screenshot), which has orientation attribute and actual placement of tooltip are not in sync
![screen shot 2017-03-16 at 5 06 21 pm](https://cloud.githubusercontent.com/assets/15674937/24023832/04ea0804-0a6c-11e7-8909-a450ccaf5001.png)

## Code examples help us better understand the issue - follow the appropriate codepen for the component by going to https://predix-ui.com, finding the component in question, and clicking on the pencil icon under the demo.
        Once you've created your code example, you can save it under a new url.
        Please note that you should NOT use the same methods for production as the ones used in codepen - these methods are not production ready.

**Comment by benoitjchevalier** [comment]
Hello,

I can't seem to be able to reproduce ion codepen (or demo). The tooltip follows the `orientation` property. Were you using any other options?

**Comment by gedesigntech** [comment]
My bad, I had "orientation" set twice (first "auto", then "bottom") in the screenshot.  I guess it takes the first one.  You can close this if that's the correct behavior (e.g., take the first one and ignore subsequent ones).  Thanks
