### ISSUE TITLE
Tooltip not working after drag and drop using polymer-dragula

### ISSUE THREAD

**Issue by rkannan86** [PredixDev/px-tooltip#21]
I'm using Polymer dragula (https://github.com/ergo/polymer-dragula.git#0.1.1) component to drag and drop the section. Inside that I'm using Px-tooltip(v0.10.18), So after drag and drop the section tooltip's are not displaying.

Before drag and drop its working fine.

**Comment by nonmetalhail** [comment]
Closing due to:
1) lack of working demo of the issue
2) possibly an issue with Polymer dragula
3) Polymer dragula doesnt appear to be actively maintained and doesnt work in shadow dom.
