### ISSUE TITLE
px-tooltip disappears from D3 charts

### ISSUE THREAD

**Issue by darshil-ge** [PredixDev/px-tooltip#23]
px-tooltip disappears from the data point in D3 charts, on performing some actions on the chart (eg zooming, reset, etc).
The tool tip is removed from dom itself.

![pristine](https://user-images.githubusercontent.com/29941926/27900888-9b85f1b8-624d-11e7-8ebd-09bb0a1e727c.jpg)

![tooltip-removed](https://user-images.githubusercontent.com/29941926/27900899-a551c230-624d-11e7-99d5-a928d1dd9bca.jpg)

Thanks in advance
Darshil

**Comment by darshil-ge** [comment]
@randyaskin Can you please help me out here?

**Comment by randyaskin** [comment]
This is the intended behavior. If you zoom or reset the map, your cursor is likely not going to be hovering over the same point anymore, so the tooltip disappears.
