### ISSUE TITLE
css broken in v1.0.0-prerelease-6

### ISSUE THREAD

**Issue by davidsteinberger** [PredixDev/px-tooltip#24]
Sorry to go off the regular template, but I just realized that _v1.0.0-prerelease-6_ does not have the proper css. The style module is missing the styles from `px-helpers-design/_generic.helpers.scss`.
For people on the bleeding edge it's easy to go with _v1.0.0-prerelease-5_, but I thought I report it anyways.

**Comment by nonmetalhail** [comment]
Interesting. Not sure what happened there. Just rebuilt the css and pushed as -7. Let me know if that does not fix it.
