### ISSUE TITLE
Tooltip doesn't auto-close if associated element is disabled

### ISSUE THREAD

**Issue by kylepope-ge** [PredixDev/px-tooltip#29]
## Expected behavior and actual behavior:
Actual behavior: hovering over an active button causes the tooltip to show (good), but if that button becomes disabled, tool tip will remain open even after the cursor leaves the button's bounds.
Expected behavior: tooltip continues to auto-close even if the associated element is disabled.

## Steps to reproduce the problem:
1. Associate a button with a px-tooltip to show when you hover over the button.
2. In the button click handler, disable the button.
3. You will notice that the px-tooltip will never close even if you move your mouse away, because the button is disabled.

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
Component version number: 1.0.5
Browser: 63.0.3239.132 (Official Build) (64-bit)
Operating System: Mac OS
Hardware: MacBook Pro 15 inch.

## Other Comments:
I believe the root cause is because mouseenter/mouseleave events do not fire for disabled elements, which is pretty annoying. If there's not a fix for this, is there a recommended workaround?

**Comment by randyaskin** [comment]
Predix buttons from px-buttons-design don't use the `disabled` attribute, they use a `btn--disabled` class instead to control the visual style and interactivity of "disabled" buttons. I've tested px-tooltip with these buttons by adding the class while the tooltip is visible, and it does go away as expected on mouseleave. 

We have no control over the behavior of native HTML5 buttons, it seems that you are correct that they don't fire mouseenter and mouseleave events when the `disabled` attribute is set.
