### ISSUE TITLE
Tooltip does not scale with a lot of text

### ISSUE THREAD

**Issue by arcpato** [PredixDev/px-tooltip#7]
When the content of the tooltip is large, the container width keeps expanding beyond the viewport.

There are some design implications to define the max width of the tooltip so the text wraps around once that limit is hit.

![screen shot 2016-05-05 at 3 10 28 pm 2](https://cloud.githubusercontent.com/assets/6137443/15059123/9c55e648-12d5-11e6-8686-b8c154e24ea9.png)

**Comment by nonmetalhail** [comment]
That's funny; last week I almost jokingly assigned this to you saying, "I have faith in your ability to fix this"  ;)

**Comment by runn-vermel** [comment]
PR fixed this.
