### ISSUE TITLE
Tooltip is not hidden when it is on clickable item

### ISSUE THREAD

**Issue by 212402415** [PredixDev/px-tooltip#9]
We have clickable data in the data table(px-data-table) which has a tooltip to it. When we wait for a while till the tooltip comes up and click on the link,(as shown below)

<img width="1121" alt="screen shot 2016-05-13 at 2 42 16 pm" src="https://cloud.githubusercontent.com/assets/19353085/15263045/5664506a-191b-11e6-87c6-be8fb72b6800.png">

And the tooltip remains there even page navigates to next and remains there for ever, until we refresh the page as seen below,
<img width="979" alt="screen shot 2016-05-13 at 2 38 00 pm" src="https://cloud.githubusercontent.com/assets/19353085/15263137/01f9fc4a-191c-11e6-9179-cabc9819d46e.png">

**Comment by 212402415** [comment]
Please find the pull request labelled 'Fix Tooltip not hidden on link item' to fix this issue.

**Comment by runn-vermel** [comment]
PR fixed this.
